/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fantasygame.view;

/**
 *
 * @author leticia
 */
public class TelaInicialAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialAdministrador
     */
    public TelaInicialAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadNewFun = new javax.swing.JButton();
        btnAcomCha = new javax.swing.JButton();
        btnHistChama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadNewFun.setText("Cadastrar novo funcionário");
        btnCadNewFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadNewFunActionPerformed(evt);
            }
        });

        btnAcomCha.setText("Acompanhar chamado");
        btnAcomCha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcomChaActionPerformed(evt);
            }
        });

        btnHistChama.setText("Histórico de chamados");
        btnHistChama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistChamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadNewFun)
                .addGap(43, 43, 43)
                .addComponent(btnAcomCha)
                .addGap(41, 41, 41)
                .addComponent(btnHistChama)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHistChama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadNewFun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAcomCha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadNewFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadNewFunActionPerformed
        TelaCriarChamado telaCriarChamado = new TelaCriarChamado(); // Crie uma instância da Tela1
        telaCriarChamado.setVisible(true); // Torne a Tela1 visível
        dispose();
    }//GEN-LAST:event_btnCadNewFunActionPerformed

    private void btnAcomChaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcomChaActionPerformed
       TelaAcompanhamentodeChamado telaAcompanhamentodeChamado = new TelaAcompanhamentodeChamado(); // Crie uma instância da Tela1
        telaAcompanhamentodeChamado.setVisible(true); // Torne a Tela1 visível
        dispose();
    }//GEN-LAST:event_btnAcomChaActionPerformed

    private void btnHistChamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistChamaActionPerformed
        TelaAcompanhamentodeChamado telaAcompanhamentodeChamado = new TelaAcompanhamentodeChamado(); // Crie uma instância da Tela1
        telaAcompanhamentodeChamado.setVisible(true); // Torne a Tela1 visível
        dispose();
    }//GEN-LAST:event_btnHistChamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcomCha;
    private javax.swing.JButton btnCadNewFun;
    private javax.swing.JButton btnHistChama;
    // End of variables declaration//GEN-END:variables
}
